### ISSUE TITLE
Background messaging not working prior to Android 12

### ISSUE THREAD

**Issue by deoscode** [PeterStaev/az_notification_hub#2] opened 2024-12-23 21:47 UTC
Background handler is registered in main as documented.
Foreground message is received fine, however when I switch app to background and send same message, it fails:

Launching lib\main.dart on moto g 10 in debug mode...
Running Gradle task 'assembleDebug'...
√ Built build\app\outputs\flutter-apk\app-debug.apk
I/flutter (20692): [IMPORTANT:flutter/shell/platform/android/android_context_vk_impeller.cc(60)] Using the Impeller rendering backend (Vulkan).
Debug service listening on ws://127.0.0.1:56366/he5bnByKkyE=/ws
Syncing files to device moto g 10...
I/flutter (20692): main
D/ANH     (20692): Network 179 is available.
D/ANH     (20692): Network has been connected.
D/ANH     (20692): Network 180 is available.
I/Choreographer(20692): Skipped 175 frames!  The application may be doing too much work on its main thread.
I/flutter (20692): Opened App: {data: {}}
D/ProfileInstaller(20692): Installing profile for com.deonic.sodium
D/FANH    (20692): message received
I/flutter (20692): onMessage (foreground) : {data: {}, id: 0:1734990257426322%db4081c0db4081c0, body: message body}
I/flutter (20692): app state changed !!!!: AppLifecycleState.inactive
I/flutter (20692): app state changed !!!!: AppLifecycleState.hidden
I/flutter (20692): app state changed !!!!: AppLifecycleState.paused
I/FA      (20692): Application backgrounded at: timestamp_millis: 1734990265702
D/FANH    (20692): message received
W/FirebaseMessaging(20692): Missing Default Notification Channel metadata in AndroidManifest. Default value will be used.
I/FANH Worker(20692): Creating background FlutterEngine instance.
I/AdrenoVK-0(20692): QUALCOMM build          : 436a040394, Ie3251bda9d
I/AdrenoVK-0(20692): Build Date              : 10/14/20
I/AdrenoVK-0(20692): Shader Compiler Version : EV031.32.02.06
I/AdrenoVK-0(20692): Local Branch            : 
I/AdrenoVK-0(20692): Remote Branch           : 
I/AdrenoVK-0(20692): Remote Branch           : 
I/AdrenoVK-0(20692): Reconstruct Branch      : 
I/AdrenoVK-0(20692): Build Config            : S P 10.0.7 AArch64
I/AdrenoVK-0(20692): Driver Path             : /vendor/lib64/hw/vulkan.adreno.so
I/flutter (20692): [IMPORTANT:flutter/shell/platform/android/android_context_vk_impeller.cc(60)] Using the Impeller rendering backend (Vulkan).
E/WM-WorkerWrapper(20692): Work [ id=f0947439-28d3-46f2-88a5-bccc913e5075, tags={ com.tangrainc.azure_notification_hub.AzRemoteMessageBackgroundWorker } ] failed because it threw an exception/error
E/WM-WorkerWrapper(20692): java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Expedited WorkRequests require a Worker to provide an implementation for 
E/WM-WorkerWrapper(20692):  `getForegroundInfo()`
E/WM-WorkerWrapper(20692): 	at androidx.work.impl.utils.futures.AbstractFuture.getDoneValue(AbstractFuture.java:515)
E/WM-WorkerWrapper(20692): 	at androidx.work.impl.utils.futures.AbstractFuture.get(AbstractFuture.java:474)
E/WM-WorkerWrapper(20692): 	at androidx.work.impl.WorkerWrapper$2.run(WorkerWrapper.java:316)
E/WM-WorkerWrapper(20692): 	at androidx.work.impl.utils.SerialExecutorImpl$Task.run(SerialExecutorImpl.java:96)
E/WM-WorkerWrapper(20692): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/WM-WorkerWrapper(20692): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/WM-WorkerWrapper(20692): 	at java.lang.Thread.run(Thread.java:923)
E/WM-WorkerWrapper(20692): Caused by: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Expedited WorkRequests require a Worker to provide an implementation for 
E/WM-WorkerWrapper(20692):  `getForegroundInfo()`
E/WM-WorkerWrapper(20692): 	at androidx.work.impl.utils.futures.AbstractFuture.getDoneValue(AbstractFuture.java:515)
E/WM-WorkerWrapper(20692): 	at androidx.work.impl.utils.futures.AbstractFuture.get(AbstractFuture.java:474)
E/WM-WorkerWrapper(20692): 	at androidx.work.impl.WorkerWrapper$1.run(WorkerWrapper.java:298)
E/WM-WorkerWrapper(20692): 	at android.os.Handler.handleCallback(Handler.java:938)
E/WM-WorkerWrapper(20692): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/WM-WorkerWrapper(20692): 	at android.os.Looper.loop(Looper.java:250)
E/WM-WorkerWrapper(20692): 	at android.app.ActivityThread.main(ActivityThread.java:7806)
E/WM-WorkerWrapper(20692): 	at java.lang.reflect.Method.invoke(Native Method)
E/WM-WorkerWrapper(20692): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/WM-WorkerWrapper(20692): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)
E/WM-WorkerWrapper(20692): Caused by: java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Expedited WorkRequests require a Worker to provide an implementation for 
E/WM-WorkerWrapper(20692):  `getForegroundInfo()`
E/WM-WorkerWrapper(20692): 	at androidx.work.impl.utils.futures.AbstractFuture.getDoneValue(AbstractFuture.java:515)
E/WM-WorkerWrapper(20692): 	at androidx.work.impl.utils.futures.AbstractFuture.get(AbstractFuture.java:474)
E/WM-WorkerWrapper(20692): 	at androidx.work.impl.utils.WorkForegroundRunnable$1.run(WorkForegroundRunnable.java:100)
E/WM-WorkerWrapper(20692): 	... 7 more
E/WM-WorkerWrapper(20692): Caused by: java.lang.IllegalStateException: Expedited WorkRequests require a Worker to provide an implementation for 
E/WM-WorkerWrapper(20692):  `getForegroundInfo()`
E/WM-WorkerWrapper(20692): 	at androidx.work.Worker.getForegroundInfo(Worker.java:127)
E/WM-WorkerWrapper(20692): 	at androidx.work.Worker$2.run(Worker.java:100)
E/WM-WorkerWrapper(20692): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/WM-WorkerWrapper(20692): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/WM-WorkerWrapper(20692): 	at java.lang.Thread.run(Thread.java:923)
I/WM-WorkerWrapper(20692): Worker result FAILURE for Work [ id=f0947439-28d3-46f2-88a5-bccc913e5075, tags={ com.tangrainc.azure_notification_hub.AzRemoteMessageBackgroundWorker } ]

**Comment by deoscode** [comment] 2024-12-23 22:06
I tried the same scenario using your main.dart code and got same failure symptoms:
Launching lib\main.dart on moto g 10 in debug mode...
Running Gradle task 'assembleDebug'...
√ Built build\app\outputs\flutter-apk\app-debug.apk
Installing build\app\outputs\flutter-apk\app-debug.apk...
I/flutter (24759): [IMPORTANT:flutter/shell/platform/android/android_context_vk_impeller.cc(60)] Using the Impeller rendering backend (Vulkan).
Debug service listening on ws://127.0.0.1:57782/vrVZjwEMqVo=/ws
Syncing files to device moto g 10...
I/flutter (24759): main
D/ANH     (24759): Network 179 is available.
D/ANH     (24759): Network has been connected.
I/flutter (24759): Opened App: {data: {}}
I/Choreographer(24759): Skipped 183 frames!  The application may be doing too much work on its main thread.
D/ProfileInstaller(24759): Installing profile for com.deonic.sodium
I/ANH     (24759): updated installation
D/ANH     (24759): Network 180 is available.
D/FANH    (24759): message received
I/flutter (24759): onMessage: {data: {}, id: 0:1734991428426225%db4081c0db4081c0, body: message body}
I/FA      (24759): Application backgrounded at: timestamp_millis: 1734991435268
D/FANH    (24759): message received
W/FirebaseMessaging(24759): Missing Default Notification Channel metadata in AndroidManifest. Default value will be used.
I/FANH Worker(24759): Creating background FlutterEngine instance.
I/AdrenoVK-0(24759): QUALCOMM build          : 436a040394, Ie3251bda9d
I/AdrenoVK-0(24759): Build Date              : 10/14/20
I/AdrenoVK-0(24759): Shader Compiler Version : EV031.32.02.06
I/AdrenoVK-0(24759): Local Branch            : 
I/AdrenoVK-0(24759): Remote Branch           : 
I/AdrenoVK-0(24759): Remote Branch           : 
I/AdrenoVK-0(24759): Reconstruct Branch      : 
I/AdrenoVK-0(24759): Build Config            : S P 10.0.7 AArch64
I/AdrenoVK-0(24759): Driver Path             : /vendor/lib64/hw/vulkan.adreno.so
I/flutter (24759): [IMPORTANT:flutter/shell/platform/android/android_context_vk_impeller.cc(60)] Using the Impeller rendering backend (Vulkan).
E/WM-WorkerWrapper(24759): Work [ id=412f6cf9-a489-4500-b6c1-eff035efd2ff, tags={ com.tangrainc.azure_notification_hub.AzRemoteMessageBackgroundWorker } ] failed because it threw an exception/error
E/WM-WorkerWrapper(24759): java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Expedited WorkRequests require a Worker to provide an implementation for 
E/WM-WorkerWrapper(24759):  `getForegroundInfo()`
E/WM-WorkerWrapper(24759): 	at androidx.work.impl.utils.futures.AbstractFuture.getDoneValue(AbstractFuture.java:515)
E/WM-WorkerWrapper(24759): 	at androidx.work.impl.utils.futures.AbstractFuture.get(AbstractFuture.java:474)
E/WM-WorkerWrapper(24759): 	at androidx.work.impl.WorkerWrapper$2.run(WorkerWrapper.java:316)
E/WM-WorkerWrapper(24759): 	at androidx.work.impl.utils.SerialExecutorImpl$Task.run(SerialExecutorImpl.java:96)
E/WM-WorkerWrapper(24759): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/WM-WorkerWrapper(24759): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/WM-WorkerWrapper(24759): 	at java.lang.Thread.run(Thread.java:923)
E/WM-WorkerWrapper(24759): Caused by: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Expedited WorkRequests require a Worker to provide an implementation for 
E/WM-WorkerWrapper(24759):  `getForegroundInfo()`
E/WM-WorkerWrapper(24759): 	at androidx.work.impl.utils.futures.AbstractFuture.getDoneValue(AbstractFuture.java:515)
E/WM-WorkerWrapper(24759): 	at androidx.work.impl.utils.futures.AbstractFuture.get(AbstractFuture.java:474)
E/WM-WorkerWrapper(24759): 	at androidx.work.impl.WorkerWrapper$1.run(WorkerWrapper.java:298)
E/WM-WorkerWrapper(24759): 	at android.os.Handler.handleCallback(Handler.java:938)
E/WM-WorkerWrapper(24759): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/WM-WorkerWrapper(24759): 	at android.os.Looper.loop(Looper.java:250)
E/WM-WorkerWrapper(24759): 	at android.app.ActivityThread.main(ActivityThread.java:7806)
E/WM-WorkerWrapper(24759): 	at java.lang.reflect.Method.invoke(Native Method)
E/WM-WorkerWrapper(24759): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/WM-WorkerWrapper(24759): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)
E/WM-WorkerWrapper(24759): Caused by: java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Expedited WorkRequests require a Worker to provide an implementation for 
E/WM-WorkerWrapper(24759):  `getForegroundInfo()`
E/WM-WorkerWrapper(24759): 	at androidx.work.impl.utils.futures.AbstractFuture.getDoneValue(AbstractFuture.java:515)
E/WM-WorkerWrapper(24759): 	at androidx.work.impl.utils.futures.AbstractFuture.get(AbstractFuture.java:474)
E/WM-WorkerWrapper(24759): 	at androidx.work.impl.utils.WorkForegroundRunnable$1.run(WorkForegroundRunnable.java:100)
E/WM-WorkerWrapper(24759): 	... 7 more
E/WM-WorkerWrapper(24759): Caused by: java.lang.IllegalStateException: Expedited WorkRequests require a Worker to provide an implementation for 
E/WM-WorkerWrapper(24759):  `getForegroundInfo()`
E/WM-WorkerWrapper(24759): 	at androidx.work.Worker.getForegroundInfo(Worker.java:127)
E/WM-WorkerWrapper(24759): 	at androidx.work.Worker$2.run(Worker.java:100)
E/WM-WorkerWrapper(24759): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/WM-WorkerWrapper(24759): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/WM-WorkerWrapper(24759): 	at java.lang.Thread.run(Thread.java:923)
I/WM-WorkerWrapper(24759): Worker result FAILURE for Work [ id=412f6cf9-a489-4500-b6c1-eff035efd2ff, tags={ com.tangrainc.azure_notification_hub.AzRemoteMessageBackgroundWorker } ]

**Comment by PeterStaev** [comment] 2024-12-24 08:38
@deoscode to eliminate the possibility of a misconfig, can you try the the sameple app in this repo and just change the Azure Notification hub settings so you can test with your hub. 

Also please provide what version of flutter are you using as well the version of android.

**Comment by deoscode** [comment] 2024-12-24 14:22
An update.

I cloned a fresh version of your repo.
Opened the example folder in android studio
updates using my google-services.json
update AndroidManifest.xml to use my azure hub settings.
changed the build.gradle to use my google services application id.

Build.gradle
    defaultConfig {
        applicationId = "com.deonic.sodium"

it still wouldnt build with compileSdk=35
Switched it down to 34 in build.gradle, as below

android {
    namespace = "com.tangrainc.azure_notification_hub_example"
    compileSdk = 34
    ndkVersion = flutter.ndkVersion

it built and ran!
However, same symptoms as originally reported for background mesaages.

√ Built build\app\outputs\flutter-apk\app-debug.apk
Installing build\app\outputs\flutter-apk\app-debug.apk...
I/flutter (28254): [IMPORTANT:flutter/shell/platform/android/android_context_vk_impeller.cc(60)] Using the Impeller rendering backend (Vulkan).
Debug service listening on ws://127.0.0.1:52826/_kFd4yIBtSg=/ws
Syncing files to device moto g 10...
I/flutter (28254): main
D/ANH     (28254): Network 187 is available.
D/ANH     (28254): Network has been connected.
D/ANH     (28254): Network 188 is available.
I/Choreographer(28254): Skipped 174 frames!  The application may be doing too much work on its main thread.
I/flutter (28254): Opened App: {data: {}}
D/ProfileInstaller(28254): Installing profile for com.deonic.sodium
I/Choreographer(28254): Skipped 34 frames!  The application may be doing too much work on its main thread.
D/FANH    (28254): message received
I/flutter (28254): onMessage: {data: {}, id: 0:1735049656275762%db4081c0db4081c0, body: message body}
W/FirebaseMessaging(28254): Unable to log event: analytics library is missing
W/FirebaseMessaging(28254): Unable to log event: analytics library is missing
D/FANH    (28254): message received
W/FirebaseMessaging(28254): Unable to log event: analytics library is missing
W/FirebaseMessaging(28254): Missing Default Notification Channel metadata in AndroidManifest. Default value will be used.
I/FANH Worker(28254): Creating background FlutterEngine instance.
I/AdrenoVK-0(28254): QUALCOMM build          : 436a040394, Ie3251bda9d
I/AdrenoVK-0(28254): Build Date              : 10/14/20
I/AdrenoVK-0(28254): Shader Compiler Version : EV031.32.02.06
I/AdrenoVK-0(28254): Local Branch            : 
I/AdrenoVK-0(28254): Remote Branch           : 
I/AdrenoVK-0(28254): Remote Branch           : 
I/AdrenoVK-0(28254): Reconstruct Branch      : 
I/AdrenoVK-0(28254): Build Config            : S P 10.0.7 AArch64
I/AdrenoVK-0(28254): Driver Path             : /vendor/lib64/hw/vulkan.adreno.so
I/flutter (28254): [IMPORTANT:flutter/shell/platform/android/android_context_vk_impeller.cc(60)] Using the Impeller rendering backend (Vulkan).
E/WM-WorkerWrapper(28254): Work [ id=ca121068-d68c-41f4-bc6a-60b13a59f15c, tags={ com.tangrainc.azure_notification_hub.AzRemoteMessageBackgroundWorker } ] failed because it threw an exception/error
E/WM-WorkerWrapper(28254): java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Expedited WorkRequests require a Worker to provide an implementation for 
E/WM-WorkerWrapper(28254):  `getForegroundInfo()`
E/WM-WorkerWrapper(28254): 	at androidx.work.impl.utils.futures.AbstractFuture.getDoneValue(AbstractFuture.java:515)
E/WM-WorkerWrapper(28254): 	at androidx.work.impl.utils.futures.AbstractFuture.get(AbstractFuture.java:474)
E/WM-WorkerWrapper(28254): 	at androidx.work.impl.WorkerWrapper$2.run(WorkerWrapper.java:316)
E/WM-WorkerWrapper(28254): 	at androidx.work.impl.utils.SerialExecutorImpl$Task.run(SerialExecutorImpl.java:96)
E/WM-WorkerWrapper(28254): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/WM-WorkerWrapper(28254): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/WM-WorkerWrapper(28254): 	at java.lang.Thread.run(Thread.java:923)
E/WM-WorkerWrapper(28254): Caused by: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Expedited WorkRequests require a Worker to provide an implementation for 
E/WM-WorkerWrapper(28254):  `getForegroundInfo()`
E/WM-WorkerWrapper(28254): 	at androidx.work.impl.utils.futures.AbstractFuture.getDoneValue(AbstractFuture.java:515)
E/WM-WorkerWrapper(28254): 	at androidx.work.impl.utils.futures.AbstractFuture.get(AbstractFuture.java:474)
E/WM-WorkerWrapper(28254): 	at androidx.work.impl.WorkerWrapper$1.run(WorkerWrapper.java:298)
E/WM-WorkerWrapper(28254): 	at android.os.Handler.handleCallback(Handler.java:938)
E/WM-WorkerWrapper(28254): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/WM-WorkerWrapper(28254): 	at android.os.Looper.loop(Looper.java:250)
E/WM-WorkerWrapper(28254): 	at android.app.ActivityThread.main(ActivityThread.java:7806)
E/WM-WorkerWrapper(28254): 	at java.lang.reflect.Method.invoke(Native Method)
E/WM-WorkerWrapper(28254): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/WM-WorkerWrapper(28254): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)
E/WM-WorkerWrapper(28254): Caused by: java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Expedited WorkRequests require a Worker to provide an implementation for 
E/WM-WorkerWrapper(28254):  `getForegroundInfo()`
E/WM-WorkerWrapper(28254): 	at androidx.work.impl.utils.futures.AbstractFuture.getDoneValue(AbstractFuture.java:515)
E/WM-WorkerWrapper(28254): 	at androidx.work.impl.utils.futures.AbstractFuture.get(AbstractFuture.java:474)
E/WM-WorkerWrapper(28254): 	at androidx.work.impl.utils.WorkForegroundRunnable$1.run(WorkForegroundRunnable.java:100)
E/WM-WorkerWrapper(28254): 	... 7 more
E/WM-WorkerWrapper(28254): Caused by: java.lang.IllegalStateException: Expedited WorkRequests require a Worker to provide an implementation for 
E/WM-WorkerWrapper(28254):  `getForegroundInfo()`
E/WM-WorkerWrapper(28254): 	at androidx.work.Worker.getForegroundInfo(Worker.java:127)
E/WM-WorkerWrapper(28254): 	at androidx.work.Worker$2.run(Worker.java:100)
E/WM-WorkerWrapper(28254): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/WM-WorkerWrapper(28254): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/WM-WorkerWrapper(28254): 	at java.lang.Thread.run(Thread.java:923)
I/WM-WorkerWrapper(28254): Worker result FAILURE for Work [ id=ca121068-d68c-41f4-bc6a-60b13a59f15c, tags={ com.tangrainc.azure_notification_hub.AzRemoteMessageBackgroundWorker } ]

Have you tried running your example in background and checking the debug logs?
Which version of compileSdk are you using?

**Comment by PeterStaev** [comment] 2024-12-27 16:52
Hey @deoscode I just tested this on the API 34 emulator and I do not see the problem you are experiencing. I was running Flutter 3.24 so the example app was working fine. Tried sending a push notification (both app in the background and closed) and the handler was triggered and the message was logged. 

I then updated the example to use latest flutter SDK:
```
Flutter 3.27.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 17025dd882 (11 days ago) • 2024-12-17 03:23:09 +0900
Engine • revision cb4b5fff73
Tools • Dart 3.6.0 • DevTools 2.40.2
```

I had to adjust some build properties of the sample app in order for it to compile (those are pushed now to the repo). Then did a rebuild and tested again with app in background and closed. All is working fine:
<img width="1891" alt="image" src="https://github.com/user-attachments/assets/56b50d73-e7f4-4b5e-bc70-c4d40cb69c6d" />

I'm testing with the default Android FCM that is available in Azure portal when you try to make a test push.

**Comment by deoscode** [comment] 2024-12-27 17:37
Hi Peter,
I think its something to do with me changing the applicationId to deonic.sodium.com. 
users will not be expecting to use your google settings json  and default channels. Im not sure if your code caters for this?
I will try defaulting to your appId and see if that works.

Thanks for your help, greatly appreciated.Wishing you a happy new year.
RegardsRavi
Yahoo Mail: Search, organise, conquer 
 
  On Fri, 27 Dec 2024 at 4:52 pm, Peter ***@***.***> wrote:   


Hey @deoscode I just tested this on the API 34 emulator and I do not see the problem you are experiencing. I was running Flutter 3.24 so the example app was working fine. Tried sending a push notification (both app in the background and closed) and the handler was triggered and the message was logged.

I then updated the example to use latest flutter SDK:
Flutter 3.27.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 17025dd882 (11 days ago) • 2024-12-17 03:23:09 +0900
Engine • revision cb4b5fff73
Tools • Dart 3.6.0 • DevTools 2.40.2

I had to adjust some build properties of the sample app in order for it to compile (those are pushed now to the repo). Then did a rebuild and tested again with app in background and closed. All is working fine:
image.png (view on web)

I'm testing with the default Android FCM that is available in Azure portal when you try to make a test push.

**Comment by PeterStaev** [comment] 2024-12-27 21:04
For sure I do not expect users to use the sample app id :)

The only places where the example app id is present are in the android build gradle, iOS project and `google-services.json`. So I'm pretty sure that the problem is unrelated to changing the app id.

**Comment by PeterStaev** [comment] 2024-12-27 21:17
Please also try to run in in the emulators as it might be related to the phone and the Android version it is running. Searching for this error shows problems when using worker manager and expedited requests, but the background process that I use in the plugin is marked as non expedited, so not sure why you are getting the error. 
https://github.com/PeterStaev/az_notification_hub/blob/be8c55a21f2817037e1a3ce702809c81050eb094/android/src/main/kotlin/com/tangrainc/azure_notification_hub/AzRemoteMessageBackgroundWorker.kt#L44-L47

**Comment by deoscode** [comment] 2024-12-27 21:40
I will try downloading the virtual "Medium Phone API 35" device, as I have always used my physical device for testing.

motorola moto g(10), Android 11.0 ("R") 
arm64
api 30-ext15

**Comment by PeterStaev** [comment] 2024-12-27 21:56
Actually after re-reading the docs, I might have an idea what is going on. Seems on android 12 or less when `setExpedited()` is used it tries to create a foreground service and requires a notification to be shown to the user. I will see to refactor the code to account for this scenario. Will try to have a fix for the new year :)

**Closed** 2024-12-30 12:38 UTC
Labels: bug

**Comment by PeterStaev** [comment] 2024-12-30 12:39
@deoscode please try version 1.1.2. It should have the problem fixed.

**Comment by deoscode** [comment] 2024-12-30 14:00
Peter,
I can confirm its now working in v1.1.2

D/FANH    (31809): message received
I/flutter (31809): onMessage (foreground) : {data: {raised: 2024-12-23 22:05:01, source: Iodini, priority: 2, body: All text info, title: #99: Powered Up}, id: 0:1735567042284673%db4081c0f9fd7ecd}
I/flutter (31809): _save
I/flutter (31809): title:#99: Powered Up
I/flutter (31809): Status: Note Saved Successfully
I/flutter (31809): app state changed !!!!: AppLifecycleState.inactive
I/flutter (31809): app state changed !!!!: AppLifecycleState.hidden
I/flutter (31809): app state changed !!!!: AppLifecycleState.paused
D/FANH    (31809): message received
I/FA      (31809): Application backgrounded at: timestamp_millis: 1735567054418
I/FANH Worker(31809): Creating background FlutterEngine instance.
I/AdrenoVK-0(31809): QUALCOMM build          : 436a040394, Ie3251bda9d
I/AdrenoVK-0(31809): Build Date              : 10/14/20
I/AdrenoVK-0(31809): Shader Compiler Version : EV031.32.02.06
I/AdrenoVK-0(31809): Local Branch            : 
I/AdrenoVK-0(31809): Remote Branch           : 
I/AdrenoVK-0(31809): Remote Branch           : 
I/AdrenoVK-0(31809): Reconstruct Branch      : 
I/AdrenoVK-0(31809): Build Config            : S P 10.0.7 AArch64
I/AdrenoVK-0(31809): Driver Path             : /vendor/lib64/hw/vulkan.adreno.so
I/flutter (31809): [IMPORTANT:flutter/shell/platform/android/android_context_vk_impeller.cc(60)] Using the Impeller rendering backend (Vulkan).
I/FANH Worker(31809): Worker not started, queueing message
I/WM-WorkerWrapper(31809): Worker result SUCCESS for Work [ id=080b9148-526b-47cf-b9ac-eb1ef1b0b3f5, tags={ com.tangrainc.azure_notification_hub.AzRemoteMessageBackgroundWorker } ]
I/flutter (31809): onBackgroundMessage: {data: {raised: 2024-12-23 22:05:01, source: Iodini, priority: 2, body: All text info, title: #99: Powered Up}, id: 0:1735567057942330%db4081c0f9fd7ecd}

Thank you so much.
Wishing you a happy New Year!
